Support X-Sendfile in response to a POST request
boazsegev/iodine pull request #117
Opened 2022-01-10 22:28 UTC by shado23

I don't see why this shouldn't be supported, NGINX and Apache do allow it.

2023-04-28 21:14 UTC, fgoepel commented
It would be nice to get some feedback on this. Without this using Rails send_file in response to a post request just ends up downloading a file containing "Forbidden", which is not ideal from any angle.

2023-04-28 23:28 UTC, boazsegev commented
OMG, I'm so sorry, I totally missed this PR for some reason...

A quick look would suggest that this would be fine, but it will also effect the static file service (it will answer `POST` requests... I believe that [`POST` requests should bypass the static file service to be processed as dynamic requests](https://github.com/boazsegev/iodine/blob/0b0b47fc0475afec4c448cb98e28e715df91ac53/ext/iodine/http_internal.c#L45-L51), no?

If we want `X-Sendfile` to work when responding to `POST` (but still be ignored by the static file service), that the PR should probably place this conditional in the `http_on_request_handler______internal` handler just before the call to `http_sendfile2`:

```c
 /* untested, written into the text box at GitHub, so... */
  if (settings->public_folder &&
      (fiobj_obj2cstr(h->method).len != 4 || !strncasecmp("post", fiobj_obj2cstr(h->method).data, 4))) {
    fio_str_info_s path_str = fiobj_obj2cstr(h->path);
    if (!http_sendfile2(h, settings->public_folder,
                        settings->public_folder_length, path_str.data,
                        path_str.len))
      return;
  }
```

2023-04-28 23:30 UTC, boazsegev requested changes
This will route `POST` requests to the static file service as well. To prevent that we need to first edit the `http_on_request_handler______internal` function as I detailed in my comment to the PR, than we can merge this.

2023-04-29 14:45 UTC, closed without merging

2023-04-29 14:51 UTC, fgoepel commented
> OMG, I'm so sorry, I totally missed this PR for some reason...

No worries.

I didn't manage to push to this PR's branch for some reason, so I've opened #141 with the requested changes.

2023-04-29 14:53 UTC, fgoepel commented
I manually tested that it makes X-Sendfile work for POST requests.