Support X-Sendfile in response to a POST request
boazsegev/iodine pull request #141
Opened 2023-04-29 14:49 UTC by fgoepel

I didn't manage to push to the existing branch and deleting it automatically closed the pull request so I'm opening a new PR with the requested changes.

2023-04-29 15:00 UTC, boazsegev requested changes
Perfect, almost done :)

2023-04-30 16:04 UTC, fgoepel commented on ext/iodine/http_internal.c
> +      (fiobj_obj2cstr(h->method).len != 4 || !strncasecmp("post", fiobj_obj2cstr(h->method).data, 4))) {
I think you're right. I've made the change and pushed again.

Another alternative might be to ` !strncasecmp("head", ...`, as that seems to be the only case we want to accept here, that's not already rejected by `len != 4`. But in the end that would only make a difference if a new HTTP method with 4 letters were to get added later.

2023-05-01 19:05 UTC, boazsegev approved these changes

2023-05-01 19:06 UTC, merged

2023-05-01 19:06 UTC, boazsegev commented
Perfect, thanks!

2023-05-01 19:16 UTC, boazsegev commented
Done. I released the patched version. Enjoy :)

2023-05-01 20:21 UTC, fgoepel commented
Thanks.